[package]
name = "panics"
version = "0.1.0"
edition = "2021"

[dependencies]
helpers = { path = "../../../helpers" }
tracing-subscriber = { version = "0.3", features = ["fmt"] }
tracing-panic = "0.1"
