[package]
name = "structured"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
helpers = { path = "../../../helpers" }

[dev-dependencies]
serde_json = "1"